### ISSUE TITLE
Wrong Establishing connection calculations

### ISSUE THREAD

**Issue by avramenkovladyslav** [nathanielvarona/pritunl-client-github-action#114]
### Issue Description
If `established-connection-timeout` set, then it will require another time in seconds unlike what is specified and checks step increased each time in geometry progression, but steps count will be correct

1. set `established-connection-timeout` 180
2. trigger workflow
3. see how long it will require to process (more than 10 minutes)

or

1. set `established-connection-timeout` 10
2. trigger workflow
3. will be completed less than 10 seconds

checks equals seconds

checks not equals seconds

Used latest version with `nathanielvarona/pritunl-client-github-action@main` which equals `1.4.3`

### It has been used with the following parameters:
**Runner Virtual Environments:**
- Linux
  - [x] Ubuntu 22.04
  - [x] Ubuntu 20.04
- macOS
  - [ ] macOS 12
  - [ ] macOS 11
- Windows
  - [ ] Windows 2022
  - [ ] Windows 2019

**VPN Modes:**
- [x] OpenVPN (ovpn) 
- [ ] WireGuard (wg)

**Client Versions:**
- [x] Installed from the package manager 

**Start Connection:** *If the connection is started on the setup step.*
- [x] True
- [ ] False

**Runner Types:**
- [x] Tested on GitHub-hosted runner

**Comment by nathanielvarona** [comment]
Hello @avramenkovladyslav,

The input `established-connection-timeout` currently (as of release [v1.4.3](https://github.com/nathanielvarona/pritunl-client-github-action/releases/tag/v1.4.3)) is based on the number of probes/checks and not a timely-based unit (seconds).

I'll be working on that sooner or later using the time unit as our timeout.

Please star/watch the project to keep updated on the latest releases including the improvement/fixes of the current issue(s).

**Comment by nathanielvarona** [comment]
Closing the Issue Fixed from #133
