### ISSUE TITLE
No Proper instruction to download the profile file 

### ISSUE THREAD

**Issue by Elangkumaran15** [nathanielvarona/pritunl-client-github-action#175]
### It has been used with the following parameters:

**Runner Virtual Environments:**
- Linux
  - [x] Ubuntu 22.04
  - [ ] Ubuntu 20.04
- macOS
  - [ ] macOS 12
  - [ ] macOS 11
- Windows
  - [ ] Windows 2022
  - [ ] Windows 2019

**VPN Modes:**
- [x] OpenVPN (ovpn) 
- [ ] WireGuard (wg)

**Client Versions:**
- [x] Installed from the package manager 
- Version specific
  
  - [ ] 1.3.3637.72

**Start Connection:** *If the connection is started on the setup step.*
- [x] True 
- [ ] False

**Runner Types:**
- [x] Tested on GitHub-hosted runner 
- Tested on Self-Hosted runner

  *If it runs on a self-hosted runner:*
  - [ ] Manage Self-hosted
  - [ ] Action Runner Controller (ARC) (a Kubernetes Operator)

**Comment by Elangkumaran15** [comment]
Please let me know where is the Profile file to download

**Comment by nathanielvarona** [comment]
Hello @Elangkumaran15,

Pritunl VPN is an Enterprise VPN Product, the profile file should be provided by your `Infra Team` such as `DevOps` or `SRE` personnel.

If the `Infra Team` provided you with the link, it looks similar to this link  https://docs.pritunl.com/docs/connecting#user-profile-links
