### ISSUE TITLE
[QUESTION] Working with SSO profiles

### ISSUE THREAD

**Issue by JonathanPartain** [nathanielvarona/pritunl-client-github-action#207]
We are using sso to authenticate against the pritunl server. Is there any way to add support for this, or is some sort of workaround a better idea? Thanks!

**Comment by nathanielvarona** [comment]
Hello @JonathanPartain, 

Unfortunately, the action is not tested yet to support SSO. If I have a chance I will reconfigure my server to use it especifically the Google Workspace as an external Id for me to test on.

The possible flow would be:
1. The SSO Link will be copied from the GitHub Actions Logs.
2. Once succesfully authenticated from the user end, the actions continue the connection test untill fully connected.

Hopefully the `pritunl-client` CLI has this feature to pvoide SSO Link on an Standard Output.

If you have chance can you check the list of CLI flow.

```bash
pritunl-client list --json-formatted
pritunl-client start <id>
pritunl-client list --json-formatted
```

If the ClI returns an (Standard Ouput) for SSO Link or the GUI is the only way to copy the SSO Link.

Thanks,
